import {
  FaHeart,
  FaSearch,
  FaUserGraduate,
  FaMoneyBillWave,
  FaRocket,
  FaGlobeAsia,
  FaGlobe,
  FaUsers,
  FaStar,
  FaHandsHelping,
  FaHandHoldingHeart,
  FaClock,
  FaInfoCircle,
  FaImages,
  FaGraduationCap,
  FaPhoneAlt,
  FaPhone,
  FaEnvelope,
  FaMapMarkerAlt,
  FaFacebook,
  FaYoutube,
  FaWhatsapp,
  FaInstagram,
  FaLinkedin,
  FaTwitter,
  FaTiktok,
  FaMobileAlt,
  FaUniversity,
  FaCreditCard,
  FaShieldAlt,
  FaBookOpen,
  FaHandsWash,
  FaSchool,
} from "react-icons/fa";

export const ICON_MAP = {
  FaHeart,
  FaSearch,
  FaUserGraduate,
  FaMoneyBillWave,
  FaRocket,
  FaGlobeAsia,
  FaGlobe,
  FaUsers,
  FaStar,
  FaHandsHelping,
  FaHandHoldingHeart,
  FaClock,
  FaInfoCircle,
  FaImages,
  FaGraduationCap,
  FaPhoneAlt,
  FaPhone,
  FaEnvelope,
  FaMapMarkerAlt,
  FaFacebook,
  FaYoutube,
  FaWhatsapp,
  FaInstagram,
  FaLinkedin,
  FaTwitter,
  FaTiktok,
  FaMobileAlt,
  FaUniversity,
  FaCreditCard,
  FaShieldAlt,
  FaBookOpen,
  FaHandsWash,
  FaSchool,
};

export const ICON_NAMES = Object.keys(ICON_MAP);

export function getIcon(name) {
  return ICON_MAP[name] || FaStar;
}
